n = input("what's ur name ??")
print("Ur name is "+ n + "!!")
m = int(input("Enter a number : "))
print("The number you entered is ",m)
o = float(input("Enter a float value : "))
print("the floating value you entered is ",o)